routes/web.php
<?php

/*
|| to using a Closure or controller method. Build something great!
|
*/
// --------------------------------------------------------------------------
// | Web Routes
// |--------------------------------------------------------------------------
// |
// | This file is where you may define all of the routes that are handled
// | by your application. Just tell Laravel the URIs it should respond


Route::get('/', 'AutoController@index');


Route::get('pages/modal',['uses'=>'AutoController@modal']);
Route::get('pages/carwash',['uses'=>'AutoController@carwash']);
Route::get('pages/tires',['uses'=>'AutoController@tires']);
Route::get('pages/services',['uses'=>'AutoController@services']);
;

Auth::routes();

Route::get('/home', 'HomeController@index')->middleware('authenticated');
Route::group(['middleware'=>['web']],function(){

Route::resource('cars','CarsController');
Route::resource('tires','TiresController');


});
Route::get('pages/cars',['uses'=>'CarsController@cars']);
Route::get('pages/tires',['uses'=>'TiresController@tires']);


Route::group(['middleware'=>['web']],function(){

Route::resource('home','CarsController');
Route::get('home/cars/{id}', 'CarsController@edit')->name('home.cars.edit');
Route::post('home/cars/{id}', 'CarsController@update')->name('home.cars.update');
Route::get('home/tires/{id}', 'CarsController@imgsEdit')->name('home.cars.imgedit');
Route::post('home/tires/{id}', 'CarsController@imgUpdate')->name('home.cars.imgUpdate');
// Route::resource('home','TiresController');

});
// Route::get('/home',['uses'=>'CarsController@home'])->middleware('authenticated');
//requests function name

Route::get('pages/details/{id}', 'CarsController@details');

Route::get('/home',['uses'=>'CarsController@home'])->middleware('authenticated');


// Route::get('pages/details',['uses'=>'CarsController@details']);


Route::get('pages/sendMail',['uses'=>'AutoController@sendMail']);
Route::post('pages/sendMail',['uses'=>'AutoController@postMail']);

app/Tires.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tires extends Model
{
    protected $table='tires_table';
}

app/Http/Controllers/TiresController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Tires;

class TiresController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
public function home()
    {
        $tires= Tires::paginate(2); 
        // return view('pages.cars',['cars'=> $cars]);

        return view('/home',['tires'=> $tires]);
    }

   public function tires()
    {
        $tires= Tires::all(); 
        // return view('pages.cars',['cars'=> $cars]);

        return view('pages.tires',['tires'=> $tires],compact('tires'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
           $this->validate($request,[
            'brand'=>'required',
            'model'=>'required',
            'desc'=>'required',
            'year'=>'required',
            'price'=>'required',
        
            // 'imagesss'=>'required',
             ]);

    
        $tires=new Tires;
        $tires->brand=$request->brand;
        $tires->model=$request->model;
        $tires->year=$request->year;
        $tires->desc=$request->desc;
        $tires->price=$request->price;
        // $file = $request->file('imagesss');
        // $fileName =('C:/xampp/htdocs/auto/').$file->getClientOriginalName();
        // $request->file('imagesss')->move("images/",$fileName);
        // $tires->imagesss = 'asd';

        $tires->save();
        return redirect('/home');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tires=Tires::findOrFail($id);
       $tire->delete();
       return redirect('/home');
    }
}

resources/views/tires/edit.blade.php
@extends('layouts.app')

@section('content')


@if (count($errors)>0)
<ul>
  @foreach ($errors->all() as $error )
  <li>{{ $error }}</li>
  @endforeach
</ul>
@endif

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js">
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="container">
  <div class="row">
  <div class="container" style="margin-top:10px">
            <form method="POST" action="{{route('home.tires.update', $car)}}" enctype="multipart/form-data">
            {{csrf_field()}}

              <select name="brand">
                <option value="Alfa Romeo" @if ($car->brand == 'Alfa Romeo') selected="selected" @endif >Alfa Romeo</option>
                <option value="Audi" @if ($car->brand == 'Audi') selected="selected" @endif>Audi</option>
                <option value="BMW" @if ($car->brand == 'BMW') selected="selected" @endif>BMW</option>
                <option value="Fiat" @if ($car->brand == 'Fiat') selected="selected" @endif>Fiat</option>
                <option value="Ford" @if ($car->brand == 'Ford') selected="selected" @endif>Ford</option>
                <option value="Mercedes" @if ($car->brand == 'Mercedes') selected="selected" @endif>Mercedes-Benz</option>
                <option value="Volkswagen" @if ($car->brand == 'Volkswagen') selected="selected" @endif>Volkswagen</option>
              </select> 
              <input type="text" name="model"  value="{{$car->model}}" class="form-control" placeholder="model">
              <textarea class="form-control"  name="desc" rows="5" id="desc" placeholder="desc">{{$car->desc}}</textarea>       
              <input type="number" name="year" value="{{$car->year}}" class="form-control" placeholder="year">
              <input type="number" name="price"  value="{{$car->price}}" class="form-control" placeholder="price">

                  <div class="row">
                    <div class="col-md-12">
                      <input type="file" id="imagesss" name="imagesss">
                    </div>
                  </div>

              </div>
            </div>
          
              <button type="submit" value="post"  name="cars" class="btn btn-primary">Update</button>
            </div>
        </div>
      </div>

</div>
</div>
</div>
@endsection